syntax = "proto3";

option csharp_namespace = "RVAegis";

package face_recognition;

service FaceRecognition {
  // Метод для отправки изображений и меток
  rpc SendImages (ImageRequest) returns (ImageResponse);

  // Метод для получения результатов распознавания
  rpc GetResults (ResultRequest) returns (ResultResponse);
}

// Сообщение для передачи изображений и меток
message ImageRequest {
  repeated bytes images = 1;		// Массив изображений в байтах
  repeated string labels = 2;		// Массив меток (лейблов)
}

// Ответ на отправку изображений
message ImageResponse {
  bool success = 1;					// Успешно ли приняты данные
  string message = 2;				// Сообщение
}

// Сообщение для запроса результатов
message ResultRequest {
}

// Объект камеры
message ProcessedFrame {
  bytes frame = 1;
  repeated bytes cropped_faces = 2;
  repeated string recognized_labels = 3;
}

// Сообщение с результатами распознавания каждой активной камеры
message CamerasObject {
  int32 camera_index = 1;						// Индекс камеры
  repeated ProcessedFrame frames = 2;			// Объекты камер, с кадрами, обрезанными лицами и лейблом
}

message ResultResponse {
  repeated CamerasObject response = 1;
}